services:
  magsync:
    image: ghcr.io/izzoa/magsync:latest
    container_name: magsync
    volumes:
      - /mnt/master/container/magsync/config/config.toml:/config/config.toml
      - /mnt/master/container/magsync/data:/data
      - /mnt/shelf/magazines:/magazines
    environment:
      - MAGSYNC_OUTPUT_DIR=/magazines
      - MAGSYNC_INTERVAL=6h
    restart: unless-stopped
